apiVersion: v1
kind: Service
metadata:
  name: gpt-hf-service
spec:
  type: 10.96.123.45 
  selector:
    app: gpt-hf-pod
  ports:
  - port: 8000
    targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpt-hf-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: gpt.178.128.39.210.sslip.io 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gpt-hf-service
            port:
              number: 8000